id: f4e3d49e15534449bb7df9af46df6171
initial_creation_type: ocr
source_metadata:
  volumes:
    063775046ead46fd90cbe255effcf07f:
      base_file: v059.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
